name: Publish to Open VSX Registry and Visual Studio Marketplace

on:
  release:
    types: [created]

jobs:
  check-release:
    name: Reuse check release
    uses: ./.github/workflows/check_release.yml
  build:
    name: Reuse build
    uses: ./.github/workflows/build.yml

  publish-vscode-extension:
    needs: 
      - build        
    #   - check-release

    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
